sudo: false

language: php

os:
  - linux
  - osx

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - COMPOSER_FLAGS=low
  - COMPOSER_FLAGS=high

before_script:
  - composer validate
  - if [[ "$COMPOSER_FLAGS" == "low" ]]; then composer update --prefer-lowest; fi
  - if [[ "$COMPOSER_FLAGS" == "high" ]]; then composer update; fi
  - mysql -e "DROP DATABASE IF EXISTS phinx_test; CREATE DATABASE phinx_test" -uroot

script:
 - vendor/bin/phpunit
